test:
  script:
    - make clean clean-data
    - make rm test
  artifacts:
    reports:
      junit: coverage/junit.xml

after_script:
  - bash <(curl -s https://codecov.io/bash) -t 93ba4041-0079-4870-9773-5e942e1c2e76
