version: '3'

networks:
    internal:

services:

  api:
    build: .
    restart: always
    networks:
      - internal
    ports:
      - 8000:8000

#  mysql:
#    image: mysql:8.0
#    restart: always

  mongo:
    image: mongo:4.0
    restart: always
    networks:
      - internal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:latest
    restart: always
    networks:
      - internal
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
