
all:
	@echo "deploy is currently unimplemented"
	# @echo "Please use \`make <target>' where <target> is one of"
	# @echo "  run        to run the project"
	# @echo "  clean      to clean runtime data"

clean:
	@echo "deploy is currently unimplemented"
	# find ./data/* -not -name "README.md" -a -not -name ".gitignore" -exec rm -rf {} \;

run:
	@echo "deploy is currently unimplemented"
	# docker-compose up
