# Generated by Django 2.1 on 2018-09-25 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AverageYearMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_instance_year', models.CharField(max_length=4, null=True)),
                ('average_marks', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('award_grade', models.CharField(max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Average mark for a student in a specific calendar year',
            },
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('course_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Table for matching courses to schools',
            },
        ),
        migrations.CreateModel(
            name='CourseStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_instance_year', models.CharField(max_length=4, null=True)),
                ('final_mark', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('final_grade', models.CharField(max_length=5, null=True)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_api.CourseInfo')),
            ],
            options={
                'verbose_name': 'Information about a student for a course in a specific calendar year',
            },
        ),
        migrations.CreateModel(
            name='ProgramInfo',
            fields=[
                ('program_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('program_title', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Program information (i.e information about BSc General Program)',
            },
        ),
        migrations.CreateModel(
            name='ProgressDescription',
            fields=[
                ('progress_outcome_type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('progress_outcome_type_description', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name': 'Maps progress_outcome_type codes to verbos description',
            },
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('school', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('faculty', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Table for matching schools to faculties',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('encrypted_student_no', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nationality_short_name', models.CharField(max_length=255, null=True)),
                ('home_language_description', models.CharField(max_length=30, null=True)),
                ('race_description', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('age', models.IntegerField(null=True)),
                ('secondary_school_quintile', models.CharField(max_length=5, null=True)),
                ('urban_rural_secondary_school', models.CharField(max_length=10, null=True)),
                ('secondary_school_name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Student personal information',
            },
        ),
        migrations.CreateModel(
            name='StudentPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_instance_year', models.CharField(max_length=4)),
                ('degree_complete', models.BooleanField(null=True)),
                ('encrypted_student_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_api.StudentInfo')),
                ('program_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_api.ProgramInfo')),
            ],
            options={
                'verbose_name': 'Table to keep track of which students are enrolled in which programs for which years.',
            },
        ),
        migrations.CreateModel(
            name='YearOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_instance_year', models.CharField(max_length=4)),
                ('year_of_study', models.CharField(max_length=5, null=True)),
                ('encrypted_student_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_api.StudentInfo')),
            ],
            options={
                'verbose_name': 'keeps track of which year of study each student is in in each calendar year',
            },
        ),
        migrations.AddField(
            model_name='coursestats',
            name='encrypted_student_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_api.StudentInfo'),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_api.SchoolInfo'),
        ),
        migrations.AddField(
            model_name='averageyearmarks',
            name='encrypted_student_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_api.StudentInfo'),
        ),
        migrations.AddField(
            model_name='averageyearmarks',
            name='progress_outcome_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_api.ProgressDescription'),
        ),
        migrations.AlterUniqueTogether(
            name='yearofstudy',
            unique_together={('calendar_instance_year', 'encrypted_student_no')},
        ),
        migrations.AlterUniqueTogether(
            name='studentprograms',
            unique_together={('calendar_instance_year', 'encrypted_student_no', 'program_code')},
        ),
        migrations.AlterUniqueTogether(
            name='coursestats',
            unique_together={('course_code', 'calendar_instance_year', 'encrypted_student_no')},
        ),
        migrations.AlterUniqueTogether(
            name='averageyearmarks',
            unique_together={('calendar_instance_year', 'encrypted_student_no')},
        ),
    ]
