# Generated by Django 2.1 on 2018-08-22 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('course_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_instance_year', models.CharField(max_length=4)),
                ('final_mark', models.DecimalField(decimal_places=3, max_digits=6)),
                ('final_grade', models.CharField(max_length=5)),
                ('progress_outcome_type', models.CharField(max_length=10)),
                ('award_grade', models.CharField(max_length=2)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_api.CourseInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramInfo',
            fields=[
                ('program_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('program_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('student_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nationality', models.CharField(max_length=255)),
                ('home_language', models.CharField(max_length=30)),
                ('race', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('secondary_school_quintile', models.PositiveSmallIntegerField()),
                ('average_mark', models.DecimalField(decimal_places=3, max_digits=6)),
                ('school_urban', models.CharField(max_length=10)),
                ('school_name', models.CharField(max_length=255)),
                ('program_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_api.ProgramInfo')),
            ],
        ),
        migrations.DeleteModel(
            name='Enrolment',
        ),
        migrations.AddField(
            model_name='coursestats',
            name='student_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_api.StudentInfo'),
        ),
    ]
