# Generated by Django 2.1 on 2018-08-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0002_auto_20180822_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestats',
            name='course_code',
            field=models.CharField(max_length=8),
        ),
        migrations.DeleteModel(
            name='CourseInfo',
        ),
    ]
